# Generated by Django 5.2 on 2025-05-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tag',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Pós-Edital', 'Pós-Edital'), ('Pré-Edital', 'Pré-Edital'), ('Curso', 'Curso'), ('Destaque', 'Destaque'), ('Novidade', 'Novidade')], default='Regular', max_length=20),
        ),
    ]
