# Generated by Django 5.2 on 2025-09-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_alter_produto_options_produto_ncm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupom',
            name='codigo',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
