# Generated by Django 5.2 on 2025-09-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='nfe_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID da NF-e na NFE.io'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nfe_pdf_url',
            field=models.URLField(blank=True, null=True, verbose_name='Link para o PDF da NF-e'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nfe_status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Status da NF-e'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nfe_xml_url',
            field=models.URLField(blank=True, null=True, verbose_name='Link para o XML da NF-e'),
        ),
    ]
