# Generated by Django 5.2 on 2025-09-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
    ]
